### ISSUE TITLE
README: Dependencies

### ISSUE THREAD

**Issue by SeanAlling** [neilkatahira/EE-Emerge-2020-Loopmaster#2]
Its okay to use subsections for each dependencies.  

### Software
 [Code Composer Studio V10](https://software-dl.ti.com/ccs/esd/documents/ccs_downloads.html)

Used to program MSP430 microprocesssors. Make sure when installing Code Composer that support for MSP430 is selected
 ...

**Comment by neilkatahira** [comment]
Set up subsections for software and hardware/model creation.
